POST /members HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": "teacher",
  "name": "Teacher",
  "pwd": "67890",
  "authority": "ROLE_TEACHER"
}

###

POST /members HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": "student",
  "name": "Student",
  "pwd": "12345",
  "authority": "ROLE_STUDENT"
}

